# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Student Name')),
                ('surname', models.CharField(max_length=64, verbose_name='Student Surname')),
                ('date_of_birt', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=14, verbose_name='Phone number')),
                ('address', models.CharField(max_length=255)),
                ('skype', models.CharField(max_length=64)),
                ('courses', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
