# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170321_1722'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='course', to='courses.Course'),
        ),
    ]
