# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170325_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
