# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170325_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birt',
            new_name='date_of_birth',
        ),
    ]
