"""
Django settings for pybursa project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$0kgsg-b04s&+a^lgitrtl__@d^q-+v3jbm^5e@s81$l3+pxg6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025
EMAIL_HOST_USER = 'edstrkv@gmail.com'
EMAIL_HOST_PASSWORD = ''


#logger.debug()
#logger.info()
#logger.warning()
#logger.error()
#logger.critical()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'loggers': 
    {
        'courses': {
            'handlers': ['courses_log_file'],
            'level': 'DEBUG',
        },
        'students': {
            'handlers': ['students_log_file'],
            'level': 'WARNING',
        },
    },
    'handlers': 
    {
        'courses_log_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'courses_logger.log'),
            'formatter': 'courses_format',
        },
        'students_log_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'students_logger.log'),
            'formatter': 'students_format',
        },
    },
    'formatters': {
        'courses_format': {
            'format': '%(levelname)s %(message)s'
        },
        'students_format': {
            'format': '%(levelname)s %(asctime)s %(module)s %(funcName)s %(message)s'
        }
    }
}

ADMINS = (('Eduard Striukov', 'edstrkv@gmail.com'),)

