# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170325_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
    ]
