# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
