# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='skyep',
            new_name='skype',
        ),
    ]
