# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
