# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_coach_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
