# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_coach_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
