# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_coach_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='email',
        ),
    ]
