# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0005_remove_coach_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='coach',
            name='address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='coach',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='coach',
            name='skype',
            field=models.CharField(max_length=25),
        ),
    ]
